board/urls.py
__author__ = 'scribe'

from django.conf.urls import patterns, url
from board import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView, name='index'),
    url(r'^add/$', views.AddTaskView, name='add'),
    url(r'^addcomment/$', views.AddCommentView, name='addcomment'),
    url(r'^edit/$', views.EditTaskView, name='edit'),
    url(r'^login/$','django.contrib.auth.views.login', {'template_name': 'board/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'board/logout.html'}, name='logout'),
    url(r'^profile/$', views.ProfileView, name='profile'),
    url(r'^about/$', views.AboutView, name='about'),
    url(r'^task/(?P<key>\d+)/$', views.TaskView, name ='task')
)

kanban/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^board/', include('board.urls', namespace="board")),
    url(r'^admin/', include(admin.site.urls)),
)

board/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.forms import ModelForm

class Task(models.Model):
    creator = models.ForeignKey(User, related_name='Creator')
    owner = models.ForeignKey(User, related_name='Owner')
    creation_date = models.DateTimeField('Date created', auto_now=True)
    work_date = models.DateTimeField('Worked started', blank=True, null=True)
    finished_date = models.DateTimeField('Date finished', blank=True, null=True)
    description = models.TextField(max_length=500)
    name = models.CharField(max_length=40)
    todo = 'To do'
    inprogress = 'In Progress'
    finished = 'Finished'
    state_choices = (
        (todo, 'To do'),
        (inprogress, 'In progress'),
        (finished, 'Finished'),
        )
    state = models.CharField(max_length=12, choices=state_choices, default=todo)

    def __unicode__(self):
        return self.description

class Comment(models.Model):
    author = models.ForeignKey(User, related_name='Author')
    body = models.TextField(max_length = 500)
    creation_date = models.DateTimeField('Date Created', auto_now=True)
    task_id = models.IntegerField(null = True, blank = True)

class AddTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'state', 'creator', 'owner', 'work_date', 'finished_date')

class AddCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'body', 'task_id')

board/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from board.models import Task, AddTaskForm, AddCommentForm

@login_required
def AboutView(request):
    return render(request, 'board/about.html')

def LogoutView(request):
    logout(request)
    return render(request, 'board/logout.html')

@login_required
def IndexView(request):
    current_user = request.user
    titles = ["To do", "In Progress", "Finished"]
    tasks = [Task.objects.filter(creator=current_user, state=search_state) for search_state in titles]
    titles_and_tasks = zip(titles, tasks)
    return render(request, 'board/index.html', { 'titles_and_tasks': titles_and_tasks })

@login_required
def ProfileView(request):
	user = request.user
	return render(request, 'board/profile.html', {'user': user})

@login_required
def AddTaskView(request):
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("board:index")
        else:
            print "Not Valid."
    else:
        form = AddTaskForm()
    return render(request, 'board/addtask.html', {'form': form})

@login_required
def EditTaskView(request):
    if request.method == 'POST':
        try:
            task_id = request.POST.get('task_id')
            task = Task.objects.get(id=task_id)
            if 'progress' in request.POST:
                advance_progress(task)
            elif 'regress' in request.POST:
                revert_progress(task)
            elif 'delete' in request.POST:
                task.delete()
            elif 'view_task' in request.POST:
                return redirect("board:task", task_id)
            elif 'add_comment' in request.POST:
                return redirect("board:addcomment", task_id)
        except Exception, e:
            print "Error! " + str(e)
    return redirect('board:index')

@login_required
def AddCommentView(request, task_id):
    if request.method == 'POST':
        comment_form = AddCommentForm(request.POST)
        if comment_form.is_valid():
            comment_form.save()
        else:
            print "Not Valid."
    else:
        comment_form = AddCommentForm()
    return render(request, 'board/addtask.html', {'form': comment_form})

@login_required
def TaskView(request, key):
    task = get_object_or_404(Task, pk=key)
    return render(request, 'board/taskview.html', { 'task': task })



def advance_progress(task):
    if task.state == 'To do':
        task.state = 'In Progress'
    elif task.state == 'In Progress':
        task.state = 'Finished'
    task.save()

def revert_progress(task):
    if task.state == 'In Progress':
        task.state = 'To do'
    elif task.state == 'Finished':
        task.state = 'In Progress'
    task.save()

board/templates/board/about.html
{% extends 'board/base.html' %}
{% block content %}
<div class="panel panel-default">
	<div class='panel-heading'>About</div>
	<div class="panel-body">
    	<blockquote><a href="http://en.wikipedia.org/wiki/Kanban">Kanban</a> is a simple visual methodology for organizing workflows and productivity for individuals and teams.</blockquote>
    </br>
    <p>This software is licensed under GPLv3.</p>
	</div>
	<div class="panel-footer">
		<a href="mailto:hanset@users.noreply.github.com" class='btn btn-default'>E-mail Developer</a>
	</div>
</div>
{% endblock %}

board/templates/board/addcomment.html
{% extends 'board/base.html' %}
{% block content %}

<form action="" method="POST" class="form">
    {% csrf_token %}
    <table>
        {% for field in form %}
            <div class="form-group">
                <tr><td><label for="{{ field.label }}">{{ field.label }}</label></td>
                <td>{{ field }}<td></tr>
            </div>
        {% endfor %}
        <div class="form-group">
            <tr><td><button type="submit" value="Add" class="btn btn-default">Add</button></td></tr>
        </div>
    </table>
</form>

{% endblock %}

board/templates/board/addtask.html
{% extends 'board/base.html' %}
{% block content %}

<form action="" method="POST" class="form">
    {% csrf_token %}
    <table>
        {% for field in form %}
            <div class="form-group">
                <tr><td><label for="{{ field.label }}">{{ field.label }}</label></td>
                <td>{{ field }}<td></tr>
            </div>
        {% endfor %}
        <div class="form-group">
            <tr><td><button type="submit" value="Add" class="btn btn-default">Add</button></td></tr>
        </div>
    </table>
</form>

{% endblock %}

board/templates/board/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Kanban</title>
	<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Kanban</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="{% url 'board:index' %}">Dash</a></li>
	        <li><a href="{% url 'board:profile' %}">Profile</a></li>
            <li><a href="{% url 'board:add' %}">Add</a></li>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="{% url 'board:about' %}">About</a></li>
			{% if user.is_authenticated %}
				<li><a href="{% url 'board:logout' %}">Logout</a></li>
			{% else %}
				<li><a href="{% url 'board:login' %}">Login</a></li>
			{% endif %}
	      </ul>
	    </div>
	  </div>
	</nav>
	<div class='container-fluid'>
	{% block content %}
	{% endblock %}
	</div>
</body>
</html>

board/templates/board/index.html
{% extends 'board/base.html' %}

{% block title %}Dashboard{% endblock %}
	
{% block content %}	
{% if titles_and_tasks %}
<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>
    {% for title, group in titles_and_tasks %}
    <div class="panel panel-success col-md-4">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">{{ title }}<a href="{% url 'board:add' %}" class="btn btn-default btn-sm pull-right">Add {{title}}</a></h3>
      </div>
      <div class="panel-body">
        <ul class='list-group'>
            {% for task in group %}
                <form method='POST' action='{% url 'board:edit' %}'>
                     {% csrf_token %}
                     <a data-toggle="popover" data-html="true" data-container="body"
                     data-trigger="focus" tabindex="0"
                     title="Creator: {{ task.creator }} Created on: {{ task.creation_date }}"
                     data-content="<form method='POST' action='{% url 'board:edit' %}'>
                               {% csrf_token %}
                               <input type='hidden' name='task_id' value='{{task.id}}'>
                               <button type='submit' class='btn btn-sm btn-default' name='view_task'>Task Details
                               </button>
                               <button type='submit' class='btn btn-sm btn-default' name='add_comment'>Add Comment
                               </button>
                               </form>">
                      {{ task.name }}
                      </a>
                     <input type='hidden' name='task_id' value='{{task.id}}'>
                     <button type='submit' class='btn btn-sm btn-default pull-right' name='progress'>
                        <span class="glyphicon glyphicon-arrow-right"></span>
                     </button>
                     <button type='submit' class='btn btn-sm btn-default pull-right' name='regress'>
                        <span class="glyphicon glyphicon-arrow-left"></span>
                     </button>
                     <button type='submit' class='btn btn-sm btn-default pull-right' name='delete'>
                        <span class="glyphicon glyphicon-remove"></span>
                     </button>
                </form>
                <li>{{ task.description }}</li>
            {% endfor %}
        </ul>
      </div>
    </div>
    {% endfor %}
{% else %}
    <p>No tasks here yet!</p>
{% endif %}
{% endblock %}

board/templates/board/login.html
{% extends 'board/base.html' %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'board:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

board/templates/board/logout.html
{% extends 'board/base.html' %}
{% block content %}
<p>You've been logged out.</p>
{% endblock %}

board/templates/board/profile.html
{% extends 'board/base.html' %}
{% block content %}
<div class="panel panel-default">
	<div class='panel-heading'>About</div>
	<div class="panel-body">
		<table class='table table-default'>
			<thead>
				</tr>
					<th>Username</th>
			    	<th>Email</th>
                    <th>First Name</th>
                    <th>Last Name</th>
			    </tr>
	    	</thead>
	    	<tbody>
	    		<tr>
	    			<td>{{ user.username }}</td>
	    			<td>{{ user.email }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
	    		</tr>
	    	</tbody>
 		</table>
	</div>
	<div class="panel-footer">
	</div>
</div>
{% endblock %}

board/templates/board/taskview.html
{% extends 'board/base.html' %}


{% block content %}	
{% block title %}Task Details{% endblock %}
{% if task %}
    <div class = "panel panel-success">
        <div class = "panel-heading">
            <h4>{{task.name}}</h4>
        </div>
        <div class = "panel-body">
            <ul>
            <li>Creator: {{ task.creator }}</li>
            <li>Owner: {{ task.owner }}</li>
            <li>Creation Date: {{ task.creation_date }}</li>
            <li>Description: {{ task.description }}</li>
            <li>State: {{ task.state }}</li>
            </ul>
        </div>
    </div>
{% else %}
    <p>No task here!</p>
{% endif %}
{% endblock %}

board/templates/board/template.html
{% extends 'board/base.html' %}
{% block content %}
{% endblock %}